development:
  adapter: mysql
  database: fnz_development
  username: root
  password: 4ganml8y 
  pool: 5
  timeout: 5000
  encoding: utf8

test:
  adapter: mysql
  database: fnz_test
  username: root
  password: 4ganml8y
  pool: 5
  timeout: 5000
  encoding: utf8
